develop:
  extends:
    file: base.yml
    service: base
  ports:
    - "35739:35729"
  environment:
    CT_URL: http://mymachine:9000
    LOCAL_URL: http://mymachine:3000
    CT_TOKEN: null
  command: develop
  links:
    - mongo
  volumes:
    - ./app:/opt/dataset/app

mongo:
  image: mongo:3.4
  container_name: dataset-mongo-develop
  command: --smallfiles
  ports:
    - "27017"
  volumes:
    - $HOME/docker/data/dataset:/data/db
  restart: always
