version: '3'
services:
  prod:
    image: vizzuality/dataset:1.1.8${STAGING}-sdg
    ports:
      - "3000"
    env_file:
      - prod.env
    command: start
    logging:
      driver: "syslog"
      options:
        syslog-address: ${SYSLOG_ADDRESS}
        tag: dataset-sdg${STAGING}
