apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: dataset
  name: dataset
spec:
  template:
    metadata:
      annotations:
        chaos.alpha.kubernetes.io/enabled: "true"
      labels:
        name: dataset
    spec:
      containers:
      - name: dataset
        image: vizzuality/dataset
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
          limits:
            memory: "512Mi"
        args:
          - start
        env:
          - name: PORT
            value: "3000"
          - name: NODE_ENV
            value: prod
          - name: NODE_PATH
            value: app/src
          - name: S3_ACCESS_KEY_ID
            value: access_key
          - name: S3_SECRET_ACCESS_KEY
            value: secret_key
          - name: STAMPERY_TOKEN
            value: token
          - name: NEWRELIC_LICENSE
            value: test
          - name: WORKERS
            value: "1"
          - name: GATEWAY_URL
            value: http://control-tower.default.svc.cluster.local
          - name: CT_URL
            value: http://control-tower.default.svc.cluster.local
          - name: LOCAL_URL
            value: http://dataset.default.svc.cluster.local:3000
          - name: GATEWAY_TOKEN
            value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Im1pY3Jvc2VydmljZSIsImNyZWF0ZWRBdCI6IjIwMTYtMDktMTQifQ.eUmM_C8WNPBk8EJS3rHo2Zc4wCmYkzyRpRyK8ZzDV2U
          - name: CT_TOKEN
            value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Im1pY3Jvc2VydmljZSIsImNyZWF0ZWRBdCI6IjIwMTYtMDktMTQifQ.eUmM_C8WNPBk8EJS3rHo2Zc4wCmYkzyRpRyK8ZzDV2U
          - name: API_VERSION
            value: v1

        ports:
          - containerPort: 3000

      restartPolicy: Always
