apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: dataset
  name: dataset
spec:
  template:
    metadata:
      annotations:
        chaos.alpha.kubernetes.io/enabled: "true"
      labels:
        name: dataset
    spec:
      containers:
      - name: dataset
        image: vizzuality/dataset
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
          limits:
            memory: "512Mi"
        args:
          - start
        env:
          - name: PORT
            value: "3000"
          - name: NODE_ENV
            value: prod
          - name: NODE_PATH
            value: app/src
          - name: LOCAL_URL
            value: http://dataset.default.svc.cluster.local:3000

        ports:
          - containerPort: 3000

      restartPolicy: Always
